### ISSUE TITLE
Issue: EuroCC2 and DiRAC Bootcamps Issues

### ISSUE THREAD

**Issue by programmah** [openhackathons-org/nways_accelerated_programming#17]
- Regarding RDF calculation, you have to scan all the pairs of atoms there, but as it's implemented it:
     - 1) overcounts **( r(ij)=r(ji) )** 
     -  2) counts self-distance, which is 0. Is it done on purpose? I'd do it like **do i = 1, N-1; do j = i+1, N**
     
-  Regarding the challenge, the OpenACC/C solution has #pragma acc parallel loop collapse(2) default(present)
  **for (i = 1; i <= m; i++)
  {
	for (j = 1; j <= n; j++)
	{
  	tmp = newarr[i * (m + 2) + j] - oldarr[i * (m + 2) + j];
  	dsq += tmp * tmp;
	}
  }**
Shouldn't dsq be declared as reduction(+:dsq)? 
- **Challenge lab** - The instructions for running the code is not clear, the block for running the serial code only works before you start editing the code - there is confusion when trying to get the serial run timing.
- Text in notebooks should be updated concerning **qdrep (nsys-rep)**. Text and execution cells should be updated concerning **-ta** for opanacc compilation.
- The HPC SDK is old and should be updated to the latest version (NVIDIA HPC SDK Version 24.3)
- Downloading profiling report and viewing on the installed nsight system GUI kind of disconnect participants from the notebooks. It is possible to install to run nsight system within the Jupyter Notebook as shown here: [link](https://pypi.org/project/jupyterlab-nvidia-nsight/)
- In ISO notebook, section "**Compile for TESLA GPU (ISO C++)**" the cell only compiles the code but doesn’t run it - whilst the lab does say "Make sure to validate the output by running the executable", I think it would be easier if that was just part of the command in the cell, similar to the earlier cells in the notebook.
- one of the solutions **(OpenACC, C_++) collapse_rdf** has a "**#pragma acc**" on the inner loop which shouldn't be there - it actually won't compile with this in it.

- The **OpenACC** notebook mentions avoiding multiple loops in a parallel region without context - would be nice to have a "why" associated with this.

**Comment by mozhgan-kch** [comment]
Addressed the below in [2e4e28b](https://github.com/openhackathons-org/nways_accelerated_programming/commit/2e4e28be4d7ca3d33ee6b86a37e6449c83f01cc8):

> In ISO notebook, section "Compile for TESLA GPU (ISO C++)" the cell only compiles the code but doesn’t run it - whilst the lab does say "Make sure to validate the output by running the executable", I think it would be easier if that was just part of the command in the cell, similar to the earlier cells in the notebook.

Updated the cells in ISO notebook

> Text in notebooks should be updated concerning qdrep (nsys-rep). Text and execution cells should be updated concerning -ta for opanacc compilation.

Removed the `qdrep` in the night systems notebook and updated all occurrences of `-ta` in OpenACC notebook

> Regarding the challenge, the OpenACC/C solution has #pragma acc parallel loop collapse(2) default(present)
for (i = 1; i <= m; i++)
{
for (j = 1; j <= n; j++)
{
tmp = newarr[i * (m + 2) + j] - oldarr[i * (m + 2) + j];
dsq += tmp * tmp;
}
}
Shouldn't dsq be declared as reduction(+:dsq)?

Left unchanged in the solutions as the compiler generates implicit `reduction(+:dsq)`
