### ISSUE TITLE
Issue:  Issues with Python notebooks

### ISSUE THREAD

**Issue by muntasers** [openhackathons-org/nways_accelerated_programming#7]
CuPy Fundamentals:
Typo in Data transfer: d_X = cp.asarray(x) should be cp.asarray(h_X).

**Comment by muntasers** [comment]
Fixed with [Merge pull request #3 from programmah/main · openhackathons-org/nways_accelerated_programming@2fc1fa7 (github.com)](https://github.com/openhackathons-org/nways_accelerated_programming/commit/2fc1fa70b18bd63099c4b1ae9c1f1cae1eb9957c)

**Comment by mozhgan-kch** [comment]
@muntasers, have you also tested after you merged it?
